URL:  "https://store.tamillexicon.com/"

SUBJECT_TAB: "பாரதியார்+பாடல்கள்/"

SUB_TAB_STRING: '''காணி நிலம் வேண்டும்
நல்லதோர் வீணை
சுட்டும் விழிச் சுடர் தான்
காக்கை சிறகினிலே
சின்னஞ் சிறு கிளியே
நின்னையே ரதி என்று
ஆசை முகம் மறந்து போச்சே
வருவாய்,வருவாய்-கண்ணா
எத்தனை கோடி இன்பம்
வீணையடி நீ யெனக்கு
தீராத விளையாட்டுப் பிள்ளை
பாப்பாப் பாட்டு
முரசு
புதுமைப் பெண்
பெண்மை
பெண்கள் விடுதலைக் கும்பி
பெண் விடுதலை
தொழில்
மறவன் பாட்டு
நாட்டுக் கல்வி
புதிய கோணங்கி
அச்சமில்லை
ஐய பேரிகை
விடுதலை-சிட்டுக்குருவி
விடுதலை வேண்டும்
உறுதி வேண்டும்
ஆத்ம ஜெயம்
காலனுக்கு உரைத்தல்
மாயையைப் பழித்தல்
சங்கு
அறிவே தெய்வம்
பரசிவ வெள்ளம்
உலகத்தை நோக்கி வினவுதல்
நான்
சித்தாந்தச் சாமி கோயில்
பக்தி
அம்மாக்கண்ணு பாட்டு
வண்டிக்காரன் பாட்டு
கடமை
அன்பு செய்தல்
சென்றது மீளாது
மனத்திற்குக் கட்டளை
மனப் பெண்
பகைவனுக்கு அருள்வாய்
தெளிவு
கற்பனையூர்'''